# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/aodv.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15meshtastic/aodv.proto\x12\nmeshtastic\"\x8d\x01\n\x0cRouteRequest\x12\x0f\n\x07rreq_id\x18\x01 \x01(\r\x12\x12\n\noriginator\x18\x02 \x01(\r\x12\x1a\n\x12originator_seq_num\x18\x03 \x01(\r\x12\x13\n\x0b\x64\x65stination\x18\x04 \x01(\r\x12\x14\n\x0c\x64\x65st_seq_num\x18\x05 \x01(\r\x12\x11\n\thop_count\x18\x06 \x01(\r\"p\n\nRouteReply\x12\x12\n\noriginator\x18\x01 \x01(\r\x12\x13\n\x0b\x64\x65stination\x18\x02 \x01(\r\x12\x14\n\x0c\x64\x65st_seq_num\x18\x03 \x01(\r\x12\x11\n\thop_count\x18\x04 \x01(\r\x12\x10\n\x08lifetime\x18\x05 \x01(\r\"K\n\nRouteError\x12=\n\x18unreachable_destinations\x18\x01 \x03(\x0b\x32\x1b.meshtastic.UnreachableNode\"4\n\x0fUnreachableNode\x12\x10\n\x08node_num\x18\x01 \x01(\r\x12\x0f\n\x07seq_num\x18\x02 \x01(\r\"\'\n\x11RouteTableRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\r\"\x84\x01\n\nRouteEntry\x12\x13\n\x0b\x64\x65stination\x18\x01 \x01(\r\x12\x10\n\x08next_hop\x18\x02 \x01(\r\x12\x11\n\thop_count\x18\x03 \x01(\r\x12\x1b\n\x13\x64\x65stination_seq_num\x18\x04 \x01(\r\x12\x10\n\x08lifetime\x18\x05 \x01(\r\x12\r\n\x05valid\x18\x06 \x01(\x08\"P\n\x12RouteTableResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\r\x12&\n\x06routes\x18\x02 \x03(\x0b\x32\x16.meshtastic.RouteEntry\"\xf7\x01\n\x04\x41ODV\x12(\n\x04rreq\x18\x01 \x01(\x0b\x32\x18.meshtastic.RouteRequestH\x00\x12&\n\x04rrep\x18\x02 \x01(\x0b\x32\x16.meshtastic.RouteReplyH\x00\x12&\n\x04rerr\x18\x03 \x01(\x0b\x32\x16.meshtastic.RouteErrorH\x00\x12\x33\n\nrt_request\x18\x04 \x01(\x0b\x32\x1d.meshtastic.RouteTableRequestH\x00\x12\x35\n\x0brt_response\x18\x05 \x01(\x0b\x32\x1e.meshtastic.RouteTableResponseH\x00\x42\t\n\x07variantB`\n\x14org.meshtastic.protoB\nAODVProtosZ\"github.com/meshtastic/go/generated\xaa\x02\x14Meshtastic.Protobufs\xba\x02\x00\x62\x06proto3')



_ROUTEREQUEST = DESCRIPTOR.message_types_by_name['RouteRequest']
_ROUTEREPLY = DESCRIPTOR.message_types_by_name['RouteReply']
_ROUTEERROR = DESCRIPTOR.message_types_by_name['RouteError']
_UNREACHABLENODE = DESCRIPTOR.message_types_by_name['UnreachableNode']
_ROUTETABLEREQUEST = DESCRIPTOR.message_types_by_name['RouteTableRequest']
_ROUTEENTRY = DESCRIPTOR.message_types_by_name['RouteEntry']
_ROUTETABLERESPONSE = DESCRIPTOR.message_types_by_name['RouteTableResponse']
_AODV = DESCRIPTOR.message_types_by_name['AODV']
RouteRequest = _reflection.GeneratedProtocolMessageType('RouteRequest', (_message.Message,), {
  'DESCRIPTOR' : _ROUTEREQUEST,
  '__module__' : 'meshtastic.aodv_pb2'
  # @@protoc_insertion_point(class_scope:meshtastic.RouteRequest)
  })
_sym_db.RegisterMessage(RouteRequest)

RouteReply = _reflection.GeneratedProtocolMessageType('RouteReply', (_message.Message,), {
  'DESCRIPTOR' : _ROUTEREPLY,
  '__module__' : 'meshtastic.aodv_pb2'
  # @@protoc_insertion_point(class_scope:meshtastic.RouteReply)
  })
_sym_db.RegisterMessage(RouteReply)

RouteError = _reflection.GeneratedProtocolMessageType('RouteError', (_message.Message,), {
  'DESCRIPTOR' : _ROUTEERROR,
  '__module__' : 'meshtastic.aodv_pb2'
  # @@protoc_insertion_point(class_scope:meshtastic.RouteError)
  })
_sym_db.RegisterMessage(RouteError)

UnreachableNode = _reflection.GeneratedProtocolMessageType('UnreachableNode', (_message.Message,), {
  'DESCRIPTOR' : _UNREACHABLENODE,
  '__module__' : 'meshtastic.aodv_pb2'
  # @@protoc_insertion_point(class_scope:meshtastic.UnreachableNode)
  })
_sym_db.RegisterMessage(UnreachableNode)

RouteTableRequest = _reflection.GeneratedProtocolMessageType('RouteTableRequest', (_message.Message,), {
  'DESCRIPTOR' : _ROUTETABLEREQUEST,
  '__module__' : 'meshtastic.aodv_pb2'
  # @@protoc_insertion_point(class_scope:meshtastic.RouteTableRequest)
  })
_sym_db.RegisterMessage(RouteTableRequest)

RouteEntry = _reflection.GeneratedProtocolMessageType('RouteEntry', (_message.Message,), {
  'DESCRIPTOR' : _ROUTEENTRY,
  '__module__' : 'meshtastic.aodv_pb2'
  # @@protoc_insertion_point(class_scope:meshtastic.RouteEntry)
  })
_sym_db.RegisterMessage(RouteEntry)

RouteTableResponse = _reflection.GeneratedProtocolMessageType('RouteTableResponse', (_message.Message,), {
  'DESCRIPTOR' : _ROUTETABLERESPONSE,
  '__module__' : 'meshtastic.aodv_pb2'
  # @@protoc_insertion_point(class_scope:meshtastic.RouteTableResponse)
  })
_sym_db.RegisterMessage(RouteTableResponse)

AODV = _reflection.GeneratedProtocolMessageType('AODV', (_message.Message,), {
  'DESCRIPTOR' : _AODV,
  '__module__' : 'meshtastic.aodv_pb2'
  # @@protoc_insertion_point(class_scope:meshtastic.AODV)
  })
_sym_db.RegisterMessage(AODV)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.meshtastic.protoB\nAODVProtosZ\"github.com/meshtastic/go/generated\252\002\024Meshtastic.Protobufs\272\002\000'
  _ROUTEREQUEST._serialized_start=38
  _ROUTEREQUEST._serialized_end=179
  _ROUTEREPLY._serialized_start=181
  _ROUTEREPLY._serialized_end=293
  _ROUTEERROR._serialized_start=295
  _ROUTEERROR._serialized_end=370
  _UNREACHABLENODE._serialized_start=372
  _UNREACHABLENODE._serialized_end=424
  _ROUTETABLEREQUEST._serialized_start=426
  _ROUTETABLEREQUEST._serialized_end=465
  _ROUTEENTRY._serialized_start=468
  _ROUTEENTRY._serialized_end=600
  _ROUTETABLERESPONSE._serialized_start=602
  _ROUTETABLERESPONSE._serialized_end=682
  _AODV._serialized_start=685
  _AODV._serialized_end=932
# @@protoc_insertion_point(module_scope)
